# Generated by Django 5.2.9 on 2025-12-24 17:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='設備ID')),
                ('name', models.CharField(max_length=100, verbose_name='設備名稱')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC地址')),
                ('status', models.CharField(choices=[('online', '在線'), ('offline', '離線'), ('error', '錯誤')], default='offline', max_length=10, verbose_name='狀態')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後在線時間')),
                ('current_effect', models.CharField(default='off', max_length=50, verbose_name='當前燈效')),
                ('brightness', models.IntegerField(default=100, verbose_name='亮度 (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備列表',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='LightEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='效果名稱')),
                ('display_name', models.CharField(max_length=100, verbose_name='顯示名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('parameters', models.JSONField(default=dict, verbose_name='參數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '燈效',
                'verbose_name_plural': '燈效列表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, verbose_name='命令')),
                ('parameters', models.JSONField(default=dict, verbose_name='參數')),
                ('success', models.BooleanField(default=False, verbose_name='成功')),
                ('response', models.TextField(blank=True, verbose_name='響應')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='執行時間')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='light_control.device', verbose_name='設備')),
            ],
            options={
                'verbose_name': '命令日誌',
                'verbose_name_plural': '命令日誌',
                'ordering': ['-created_at'],
            },
        ),
    ]
